### ISSUE TITLE
Something not work?

### ISSUE THREAD

**Issue by Biaogo94** [msbence/hackintosh-DellLatitude5400#1]

**Comment by mfolta** [comment]
Hello. @msbence which wlan card did you use? Original is Intel AX200

**Comment by msbence** [comment]
Hi!
Sorry, I messed up my README...

The WLAN card I use is BCM94360NG, bought it from ebay. Works out of the box, no bluetooth or wlan patching needed.
(First time I bought a DW1560, but I was unable to get BT working on Catalina)

**Comment by mfolta** [comment]
@msbence Thank you for your answer.
I was thinking about buying the popular DW1560.
Last year I had a hackintosh clover approach. It ended on average :) . Now everyone has jumped on openCore.

My 5400 has i7-8665u / 32GB Ram / UHD Graphics 620 / ssd Kioxia 256GB

Kioxia is not a top-flight drive. I was able to get samsung pm981a. 

How is working on macOS? are there restarts? does e.g. TimeMachine , usbc hub work?

**Comment by msbence** [comment]
@mfolta 
I use it as a dialy driver. I'm a developer and sysadmin, and I use this hackintosh for everything.
I'll update the readme soon, but in nutshell:
Mine is with i7-8265U, upgraded to 24GB ram, UHD620, and a WD Black 500G ssd. I love it.
USB-C is working, I use my laptop with a USB-C dock and multiple monitors (warning: macOS does not support MST, and my laptop does not have a TB3 controller, so I had to use a DisplayLink adapter for my 3rd display.)
TimeMachine is working perfectly.
There are no restarts, however I expected kernel panic when my machine was in sleep mode for a longer time (12h+).
Jack hotplugging does not work, but I use a BT headphone.
HDMI hotplugging does not work, but I use USB-C DisplayPort Alt Mode most of the times.

That's all. I recommend this model for hackintoshing in general :)

**Comment by msbence** [comment]
Ohh, one more thing: Touchpad. It's a pain in the .ss. I use it with VodooI2C but this way none of the buttons/trackstick are working. With VodooPS2 everything works, but no gestures. I choose VoodoI2C, but that's up to you. I have an Apple MAgic Mouse 2, works like a dream. But if you are a touchpad person, then think about this because it wont be comfortable.

**Comment by msbence** [comment]
@mfolta 
Watch out! According to the anti hacintosh buyers guide (https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html) your Samsung SSD it NOT supported :(

**Comment by mfolta** [comment]
Generally my dell will be closed and connected to Dell Docking Station WD15. 2x monitor on displayPort. 1x LAN. MagicMouse 2 and Magic Keyboard. I am currently working on macmini (2014).
As soon as I buy the BCM94360NG I will start the project :)

Samsung is not supported :( I will stay with kioxia or buy another one

Thank you for your help.

**Comment by msbence** [comment]
Hmmm... Does your docking station use MST for two displayports? Because that won't work on macOS. I bought a USB displaylink adapter for the same reason. If your model has Thunderbolt3 and your dock as well that's a different case, but I haven't heard any good about hackintosh and TB3.

**Comment by mfolta** [comment]
I'll be checking this dock but I have USB adapter displayLink. Sorry I didn't write before. 
Maybe 1x hdmi + 1x dispalyPort or 1x display + adapter USB

**Comment by mfolta** [comment]
Yes you are right. https://osxlatitude.com/forums/topic/11410-dell-latitude-7490-with-i7-8650u-intel-uhd-620-and-1920x1080-lcd-mojavecatalina/?do=findComment&comment=90288
Only 1 monitor + adapter usb
