### ISSUE TITLE
macOS Big Sur

### ISSUE THREAD

**Issue by cvega48** [msbence/hackintosh-DellLatitude5400#11]
Can we use your latest config for Big Sur 11.4?

**Comment by msbence** [comment]
Hi @cvega48 ! Yes you should be able to use it, at least I used it. The current state of the repo is for macOS Beta, so please see 7f81b6e45946668e2f3fdb0457ffe28b2a35969b or better: use the current state (oc0.7) but remove the beta stuff from boot-args. Please respond if you have any success or failure! :)

**Comment by cvega48** [comment]
Awesome. I will give it a spin in a bit. Thanks! I will download your settings for Monterrey and test on the latest Big Sur.

**Comment by cvega48** [comment]
I have the EFI you got out for this version of macOS: 11.3.1
would that one work for 11.4? no changers to do?
I just want to make sure since I want to upgrade to 11.4.

**Comment by cvega48** [comment]
Just tried it and it works great with Big Sur 11.4
Thanks!

**Comment by hankscorpio-ceo** [comment]
Thanks much for this @msbence .  I tried using OpenCore to build my own but could not get it to recognize the installed.

I am using yours with a very similar computer but I keep getting stuck at the Apple Logo with the load line not moving.  Any suggestions?

**Comment by msbence** [comment]
Hi @hankscorpio-ceo , what do you mean by very similiar computer? I strongly suggest not to use this repo other than for Latitude 5400. You should start with a guide (from scratch), like Dortania's. Of course you can borrow ideas from other repos, but every model is different in some ways. You have to understand what you are doing :)
