### ISSUE TITLE
Backlight not working with Ventura 13.4

### ISSUE THREAD

**Issue by cvega48** [msbence/hackintosh-DellLatitude5400#19]
I have updated to 13.4 and now Backlight drops when getting into macOS. I get backlight the first part of the booting process with the Apple Logo, but then it turns off and can't see anything. Works great when connected to a secondary Screen but not the main laptop screen.

Are you updating to 13.4 anytime soon?

**Comment by BillDH2k** [comment]
Latest WhateverGreen.kext fixed this issue. Also need to add "-igfxblt" to the boot arg.

**Comment by cvega48** [comment]
Update on this. 
Updating to 13.5 fixed the issue.
