### ISSUE TITLE
TrackPad not working

### ISSUE THREAD

**Issue by WhitemanE0** [msbence/hackintosh-DellLatitude5400#2]
In System Settings I enable Tap to Click and then disable it and enable again.
Than I disable force Click and haptic feedback at the bottom.
And after all trackpad buttons works fine together with trackpoint buttons

**Comment by msbence** [comment]
Thanks for the info! :)
I found it strange, but tried it without luck.
The problem is that VoodooInput does not contain wrappers for mouse buttons, and there is no button on the Magic Trackpad2 (which is emulated). Maybe your trackpad is a different one, I'm glad that yours working perfectly!

More context: https://github.com/acidanthera/bugtracker/issues/932#issuecomment-644352452

**Comment by cvega48** [comment]
msbence, can you create a custom EFI without IC2 Trackpad?

**Comment by msbence** [comment]
Hi @cvega48 , well, you just have to edit the OC config.plist. Remove/Disable all kexts related to voodooi2c (i2c, hid, gpio, input), and enable voodoops2 mouse (which is in the config, you just have to enable it.). If all works, you'll have a pretty dumb touchpad with buttons and trackstick.

**Comment by cvega48** [comment]
Awesome! Thanks for the guide. I will do just that. Thing is that with my current 5400 setup (Your EFI by the way), I dont have touchpad at all...
I have to carry around my BT mouse around or a wired one. I hope I can get at least a dumb touchpad working. I will let you know how it went. Thanks.

**Comment by cvega48** [comment]
@msbence Is there a chance you can give me a hand with the EFI without the kexts and a modified config.plist? I did it my self and cant boot off it. I must be doing something wrong. Let me know if you can give me a hand please. Thanks.

**Comment by msbence** [comment]
You can download it [here](https://mbraptor.tech/EFI_dumpTPD.zip). There is only the config.plist and the relevant things. Merge it with your EFI folder.

**Comment by cvega48** [comment]
I get an error when booting up macOS. I overwrote your last files on my EFI OC folder on a bootable USB to test. Do I need to delete any kexts? 
![image](https://user-images.githubusercontent.com/55467816/106670483-1b663d00-657b-11eb-92b7-8474ff4ea862.jpeg)

**Comment by msbence** [comment]
Well, you should enable verbose logging with `-v` in `boot-args`. That should tell something useful.

**Comment by cvega48** [comment]
This is the last thing I see upon boot:
![image](https://user-images.githubusercontent.com/55467816/106910708-7d37bb80-66cf-11eb-9e27-a8b1ed75e910.jpeg)

Then it hangs and nothing else happens.

**Comment by juniperchow** [comment]
not an issue just wanted to leave this here, disable force touch in system preferences and tpd buttons works fine at least on my specific trackpad revision

**Comment by msbence** [comment]
for me it's now working for dragging only. It is a major improvement, but it could be better. Hopefully it will, in time... :)

**Comment by jaywhojaycee** [comment]
> In System Settings I enable Tap to Click and then disable it and enable again.
> Than I disable force Click and haptic feedback at the bottom.
> And after all trackpad buttons works fine together with trackpoint buttons

Thanks bro that works for me

**Comment by enrico9034** [comment]
I fix it with different version of VoodooPS2 kext. and I removed all kext we don't need in this PR
https://github.com/msbence/hackintosh-DellLatitude5400/pull/13

**Comment by ameenjuz** [comment]
everything working in polling mode with voodooI2c.kext + AlpsHID.kext + VoodooI2CHID.kext link https://github.com/blankmac/AlpsHID/releases
remember use aplshid.kext with VoodooI2CHID.kext under release zip file
put boot arg -vi2c-force-polling

**Comment by msbence** [comment]
Eventhough I did not notice the last comment, I did exactly this, AlpsHID did the trick!
