### ISSUE TITLE
Question: How did you get "Dell Latitude 5400, 14-inch, 2019" to appear in the About This Mac section?

### ISSUE THREAD

**Issue by Trijal08** [msbence/hackintosh-DellLatitude5400#21]
@msbence
The title says it all and I am hoping that somebody could reach out to me and answer my everlasting question!

**Comment by msbence** [comment]
This is likely obsolete (since the about window was changed and this likely wont work) but answering anyways:

Locate the file named 'com.apple.SystemProfiler.plist' in  '~/Library/Preferences'. Take a copy, open that for editing, replace the model, save, and overwrite the original file.
