### ISSUE TITLE
HDMI not working

### ISSUE THREAD

**Issue by cvega48** [msbence/hackintosh-DellLatitude5400#3]
msbence. Do you have your HDMI port working? I am currently using a USB2.0 to HDMI dongle to get video out, but this is getting my computer running slow. I was just wondering if your HDMI port is working.

**Comment by msbence** [comment]
Hey! That's a fun one... Well, Whiskey Lake sucks when it comes to HDMI. Anyways: mine is working (no coldplug, eg. only works when I plug HDMI in after the boot process).

You might want to take a look here: https://github.com/msbence/hackintosh-DellLatitude5400/blob/master/OC/config.plist#L346

Use hackintool and try to map your display outs. Some guide on that: https://www.tonymacx86.com/threads/guide-acer-swift-5-sf514-53t-whiskey-lake-macos10-14-5.277618/ (midway, point D)

**Comment by msbence** [comment]
Worst case: use an USB-C (aka DisplayPort Alt Mode) to HDMI adapter, it far more reliable.

**Comment by cvega48** [comment]
I think I will end up buying a USB-C to DisplayPort cable, as my screen has a DisplayPort. Just curious, when you say plugin in the HDMI after the boot process means right after the apple logo appears? or when exactly?

**Comment by cvega48** [comment]
Is it safe to upgrade to 11.1 using your EFI?

**Comment by cvega48** [comment]
Is it safe to upgrade to 11.1 using your EFI sir?

**Comment by msbence** [comment]
Hi @cvega48 ,

Yes, it is safe to upgrade, you can see in README.md the screenshot yourself :)

Regarding HDMI: you can plug-unplug anytime AFTER you logged in (ie.: after kernel init). The USB-C to DP is fine, my suggestion: buy a (mini-)dock, this way you could win some spare USB port with a little more money.

**Comment by cvega48** [comment]
Upgraded all good. I ordered a USB-C dock that has HDMI and DP ports. Will check these out when received. Thanks for your help mate.

**Comment by msbence** [comment]
Yes, that should do it! Keep in mind, you can not use both HDMI and DP at the same time (you can, but only in mirroring mode). That's because these docks use MST which is not implemented in macOS itself.
