### ISSUE TITLE
can't get intoi opencore boot screen.

### ISSUE THREAD

**Issue by Bradley-Liu** [msbence/hackintosh-DellLatitude5400#4]
i downloaded bigsur from appstore, created the usb boot drive and copied your efi folder into efi partition.
when i resatart the computer, i can't get into opencore boot screen and the machine just restarts. how can it resolve this issue?

**Comment by msbence** [comment]
follow the instructions here: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/

**Comment by msbence** [comment]
_Closed due to inactivity._
