### ISSUE TITLE
Network port on Dell Hub notnwotking

### ISSUE THREAD

**Issue by kailaijap** [msbence/hackintosh-DellLatitude5400#5]
I am not sure how to get this fixed as this is. It part of the build 
I saw you mentioning you always had your docking on USB-C but mine works in everything as you described but just network on Hub is not working

**Comment by msbence** [comment]
Yeah, network on it sucks. They usually use a cheap controller, not even Gigabit sometimes. It's not even working for a real macbook (tested it). Is yours and expensive one? What do you mean by not working? Can you see it in System Preferences?

**Comment by msbence** [comment]
My bad. It's in the title. It's a Dell Hub. What model it is exactly?

**Comment by msbence** [comment]
_Closed due to inactivity._
