### ISSUE TITLE
Audio 

### ISSUE THREAD

**Issue by jaywhojaycee** [msbence/hackintosh-DellLatitude5400#7]
@msbence is it any way to get audio jack working

**Comment by msbence** [comment]
It works for me! :)
Could you be more specific, please? Hotplug/coldplug/not working at all? any other info?

**Comment by jaywhojaycee** [comment]
> It works for me! :)
> Could you be more specific, please? Hotplug/coldplug/not working at all? any other info?

It wasn’t working when I just plug it in

**Comment by msbence** [comment]
What if you plug the device before booting up (coldplug)?
Did the audio device show up in the list?
Does your speaker work?
Does your speaker work when the device is plugged in?

**Comment by msbence** [comment]
@jaywhojaycee shall I close this?

**Comment by jaywhojaycee** [comment]
@msbence yes and thanks for the help bro

**Comment by msbence** [comment]
@jaywhojaycee Cool, what was the solution If I may ask? :)

**Comment by jaywhojaycee** [comment]
@msbence it just started working by it self

**Comment by msbence** [comment]
wow :D okay
