### ISSUE TITLE
macOS Monterey

### ISSUE THREAD

**Issue by jaywhojaycee** [msbence/hackintosh-DellLatitude5400#9]
Hey is it possible to macos monterey and still have everything still working

**Comment by msbence** [comment]
@jaywhojaycee I was just started tinkering around the beta yesterday. Now I'm finished, please see the updated repo. Some of my settings (keylayout, git config, etc...) were lost, but nothing serius. But keep in mind: It's an early beta release! (and not much difference from big sur for now)

**Comment by jaywhojaycee** [comment]
@msbence any info on how do I update?

**Comment by jaywhojaycee** [comment]
@msbence loke how do I upgrade without losing my info

**Comment by msbence** [comment]
@jaywhojaycee obtain a beta profile at https://betaprofiles.com/ (use Safari to open the link) and macOS 12 DevBeta will appear as a regular system update. It'll download an installer app and then you can run that. It'll take around an hour to complete. Or even more, in my case the installer was "stuck" at "about one minute remaining" for an hour. A TimeMachine backup is advised though. _This is a developer build on a machine which was never intended to run macOS at all._
I didn't lost any data, only some minor settings, and the WWAN icon is not showing up on the menu bar. That's all.

**Comment by jaywhojaycee** [comment]
@msbence I don’t know I did what you said but get this screen 


![22D356ED-B877-44D3-B15D-4FBD3397AC19](https://user-images.githubusercontent.com/85727664/122820086-138c0880-d290-11eb-8dbc-790c00dde75a.jpeg)

**Comment by msbence** [comment]
@jaywhojaycee did you upgrade the EFI itself? because there were some config changes as well! (and updated kexts)

**Comment by jaywhojaycee** [comment]
@msbence no I didn’t can I do this from windows pc because I don’t have a Mac

**Comment by msbence** [comment]
@jaywhojaycee So the upgrade did finished but now you can't boot, right?
In this case: of course you can do it on Win. Assuming you have the install USB drive: just replace the EFI folder with my repos EFI folder (or at least the files that changed). If you don't have it anymore: any USB drive which uses GPT partition table and formatted to FAT32/exFAT should do it. just place my EFI folder in it, and use the boot selection (F12 (F11?)) menu to select the USB drive.

**Comment by jaywhojaycee** [comment]
@msbence thanks a lot get everything running

**Comment by cvega48** [comment]
Till this day, how stable is Monterey Beta?

**Comment by msbence** [comment]
Hi @cvega48 Pretty stable. My Finder crashes once per month, but I would say it's pretty production ready.

**Comment by cvega48** [comment]
I see you got a real Mac now. Awesome! But please share the setup when Monterrey is released. 🥇 Thanks @msbence !!!!

**Comment by cvega48** [comment]
Will you be posting the EFI for 5400 for the final release of Monterey?

**Comment by cvega48** [comment]
When trying to install macOS Monterey I am getting this:

![image](https://user-images.githubusercontent.com/55467816/140577919-b0de0a45-0b9f-4690-bb3f-5bec3b7a52f0.png)

Did you have to do something on the OpenCore settings to be able to bypass this error?

**Comment by iamdxpe** [comment]
can you share the efi for this laptop?

**Comment by msbence** [comment]
@iamdxpe yes, this is what is repo about :)

@cvega48 sorry for late reply, I will upgrade everything soon(TM). However, my existing installation just works fine with latest monterey. About the install error: maybe OC 0.7.4 (and up) and the AdviseFeatures flag will help sove it. Stay tuned :)

**Comment by cvega48** [comment]
> @iamdxpe yes, this is what is repo about :)
> 
> @cvega48 sorry for late reply, I will upgrade everything soon(TM). However, my existing installation just works fine with latest monterey. About the install error: maybe OC 0.7.4 (and up) and the AdviseFeatures flag will help sove it. Stay tuned :)

Apparently what the installation files try to do is upgrade the Hard Drive Firmware but since this is a hackintosh, original apple hard drive is not found, therefore giving that error. It could be that since you were already using the Beta, you did not encounter this error, but perhaps you would on a clean install. I am still unable to upgrade. :(

**Comment by cvega48** [comment]
@msbence I also tried with your latest EFI and under Hackintool it states we are using OC 0.64 instead of OC 0.73 that you mentioned is installed. I copied and pasted the whole EFI folder to my EFI.

**Comment by msbence** [comment]
@cvega48 I just upgraded my repo to be the latest gratest. Try now :)

**Comment by cvega48** [comment]
For some odd reason on Hackintool it still shows as Opencore v 0.6.4

![image](https://user-images.githubusercontent.com/55467816/150028141-17b2086f-f408-40cf-998b-5b74818407c5.png)


> @cvega48 I just upgraded my repo to be the latest gratest. Try now :)

**Comment by cvega48** [comment]
Regardless it shows as 0.6.4, I have Monterey(12.1) working very well with your EFI sir! Thanks!! Using Latitude 5400 + Fenvi Wireless card for Airdrop + Bluetooth. (BCM94360NG)

![image](https://user-images.githubusercontent.com/55467816/150556060-69ea8a6b-fd6c-474c-9f32-034d007fe440.png)


https://www.aliexpress.com/item/32464748097.html?spm=a2g0o.9042311.0.0.27424c4dDFAGHY

**Comment by cvega48** [comment]
Anyone update to 12.3?

**Comment by msbence** [comment]
Sorry for being late, at least now it works even with 15.0.1 :D
